### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by Rukeith** [apidoc/apidoc#952]
# Describe the bug
I download the example folder and install the latest apidoc. And run command to generate apidoc. But I got the error. 

# Steps to reproduce

1. download example folder and put on `doc` folder
2. Install apidoc `npm i apidoc`
3. Run command `apidoc -i doc -o apidoc`

# Information

- Version of apidoc: `^0.27.0`
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS Big SUr 11.2.3

Error output

```
{"message":"parser plugin 'apiquery' not found in block: 0 in file: doc/example.js","level":"warn"}
{"message":"parser plugin 'apiquery' not found in block: 1 in file: doc/example.js","level":"warn"}
{"message":"parser plugin 'apibody' not found in block: 1 in file: doc/example.js","level":"warn"}
{"message":"parser plugin 'apiquery' not found in block: 3 in file: doc/example.js","level":"warn"}
```

**Comment by mak1986** [comment]
I'm trying to write my own api doc and I can confirm that I'm getting the same warnings. The output doc is also missing the query and body fields.

**Comment by mak1986** [comment]
For some reason apodic-core v0.12 is getting installed instead of v0.15. I tried to change package.json file to install v.015 but I'm still getting the same error.

**Comment by mak1986** [comment]
Here lies the problem: https://github.com/apidoc/apidoc/blob/59ba42548f043be0d54b7bef47a7af9a11e1dac5/package-lock.json#L2958

We are getting v0.12 installed which doesn't have these 2 parsers.

**Comment by rottmann** [comment]
Fixed in 0.27.1

**Comment by mak1986** [comment]
@rottmann The problem isn't entirely fixed. I'm not getting any warnings now but the UI doesn't show the body and query fields.

**Comment by rottmann** [comment]
@SWheeler17 can you please review the implementation of apiQuery apiBody from (https://github.com/apidoc/apidoc-core/pull/104/files) into template file (https://github.com/apidoc/apidoc/tree/dev/template)?

**Comment by mak1986** [comment]
Hi again. Apparently the whole sections for query and body from template-single/index.html has been removed.
https://github.com/apidoc/apidoc/pull/916/commits/540664a350db759eb5e6df5875ebcc26b7324667

In apidoc-core index.js two workers are also missing.
```
 apibodytitle             : './workers/api_body_title.js',
 apiquerytitle            : './workers/api_query_title.js',
 ```

**Comment by mak1986** [comment]
Actually the template-single/index.html hasn't been changed I looked at the wrong file template/index.html which is the file being used.That's why query and body ain't rendered. Using -t flag pointing to template-single folder doesn't work either.

**Comment by SWheeler17** [comment]
@mak1986, I am a bit confused, is the issue with the single page template or the multi-page template?

**Comment by SWheeler17** [comment]
Assuming that this issue is related to the multi-page template, and not the single-page template... I forgot to push my implementation of apiQuery/apiBody to the multi-page template after the single-page template was merged. I just created the PR above for the multipage template.

**Comment by mak1986** [comment]
@SWheeler17 The issue is template/index.html.

**Comment by Rukeith** [comment]
@SWheeler17 I use the latest version, the example is still not working at all.

**Comment by SWheeler17** [comment]
@Rukeith downloading the example folder and building the example (from master) by running `apidoc -i example -o apidoc` seems to work for me. I will continue to see if there is an issue for me though...

**Comment by NicolasCARPi** [comment]
Yes, make sure to `npm i`, too.

**Comment by SWheeler17** [comment]
After some investigation (and updating apiDoc via `npm i`), it looks like the single-page template is getting documentation info from both `example/_apidoc.js` and `example/example.js` leading to duplicate documentation. Upon removing the documentation in example/_apidoc.js` everything appears to work as expected. The muti-page template appears to not be loading the documentation though. I have attached a screen capture of the entire muti-page template output and my network in/out (the side bar is cut off, but that is part of the capture software not apiDoc).

![apiDoc-multi-page-output](https://user-images.githubusercontent.com/47996545/123665217-ee961900-d7ec-11eb-8377-e4a3e42bcffb.png)

<img width="1280" alt="apiDocNetwork" src="https://user-images.githubusercontent.com/47996545/123665550-3c128600-d7ed-11eb-8f33-ad3f7e9473d7.png">

Upon happening to check the error console before I posted this, I saw an error that the helper `if_neq` is missing from the file `handlebars.min.js`

After a quick search this error seemed to have been fixed in [this commit](https://github.com/apidoc/apidoc/commit/9087dfe3d8f281ae350c50dfeb1aa08091d528a5) for the single page template, so we may be able to apply the same patch/update to the multi page template.

The stack trace for this error is:
```
d@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:4766
b.default/<@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:9680
c@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:19853
anonymous@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300 line 29 > Function:13:129
h@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:17870
b.default/<@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:10117
c@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:19853
anonymous@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300 line 29 > Function:11:47
c@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:15429
d@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:15744
e@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:28:22748
@file://[omitted]/apidoc/utils/handlebars_helper.js?v=1624895116300:133:43
c@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:19853
anonymous@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300 line 29 > Function:54:155
c@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:15429
d@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:27:15744
e@file://[omitted]/apidoc/vendor/handlebars.min.js?v=1624895116300:28:22748
init/</<@file://[omitted]/apidoc/main.js:395:30
init/<@file://[omitted]/apidoc/main.js:346:13
init@file://[omitted]/apidoc/main.js:337:15
active@file://[omitted]/apidoc/main.js:61:17
L@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:7:674
oa@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:10:374
W.prototype.g@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:9:789
Q.prototype.start/<@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:7:1602
promise callback*Q.prototype.start@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:7:1584
ra/<@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:12:42
setTimeout handler*ra@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:11:51
qa/<@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:12:206
Fa.prototype.load/<@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:17:363
E@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:6:576
D/<@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:6:514
c@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:5:42
A/b.onload@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:5:167
EventHandlerNonNull*A@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:5:142
Fa.prototype.load@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:17:332
qa@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:12:183
pa.prototype.load@file://[omitted]/apidoc/vendor/webfontloader.js?v=1624895116300:10:577
@file://[omitted]/apidoc/main.js:58:13
execCb@file://[omitted]/apidoc/vendor/require.min.js:30:208
check@file://[omitted]/apidoc/vendor/require.min.js:18:422
enable/</<@file://[omitted]/apidoc/vendor/require.min.js:23:282
y/<@file://[omitted]/apidoc/vendor/require.min.js:8:101
emit/<@file://[omitted]/apidoc/vendor/require.min.js:24:200
x@file://[omitted]/apidoc/vendor/require.min.js:7:173
emit@file://[omitted]/apidoc/vendor/require.min.js:24:171
check@file://[omitted]/apidoc/vendor/require.min.js:20:114
enable/</<@file://[omitted]/apidoc/vendor/require.min.js:23:282
y/<@file://[omitted]/apidoc/vendor/require.min.js:8:101
emit/<@file://[omitted]/apidoc/vendor/require.min.js:24:200
x@file://[omitted]/apidoc/vendor/require.min.js:7:173
emit@file://[omitted]/apidoc/vendor/require.min.js:24:171
check@file://[omitted]/apidoc/vendor/require.min.js:20:114
enable@file://[omitted]/apidoc/vendor/require.min.js:24:68
init@file://[omitted]/apidoc/vendor/require.min.js:17:114
J@file://[omitted]/apidoc/vendor/require.min.js:14:221
completeLoad@file://[omitted]/apidoc/vendor/require.min.js:29:102
onScriptLoad@file://[omitted]/apidoc/vendor/require.min.js:30:333
EventListener.handleEvent*k.load@file://[omitted]/apidoc/vendor/require.min.js:35:197
load@file://[omitted]/apidoc/vendor/require.min.js:30:161
load@file://[omitted]/apidoc/vendor/require.min.js:18:85
fetch/<@file://[omitted]/apidoc/vendor/require.min.js:17:481
y/<@file://[omitted]/apidoc/vendor/require.min.js:8:101
```

**Comment by NicolasCARPi** [comment]
Are you using the latest from master or dev branch? Because I removed the if_neq stuff a few days ago.

**Comment by SWheeler17** [comment]
I am using master.

**Comment by NicolasCARPi** [comment]
Well, no traces of `if_neq` should remain. See 22829ed1f94a9845e7a15b0f70f209aa97d04367. Not sure where you get that error from, please make sure to start from scratch.

**Comment by SWheeler17** [comment]
The error is due to `if_neq` being called from the multi-page-template. The commit that you are referring to seems to be for the single page template. I was unable to find a similar commit to https://github.com/apidoc/apidoc/commit/22829ed1f94a9845e7a15b0f70f209aa97d04367 for the multi-page template.

**Comment by SWheeler17** [comment]
Upon changing all of the `if_neq` statements to `unless` in the multi-page template (similar to what was done in the single page template in https://github.com/apidoc/apidoc/commit/22829ed1f94a9845e7a15b0f70f209aa97d04367), I receive no more errors. @NicolasCARPi I can make a PR if you would like to review the changes have made and suggested making in this issue.

**Comment by NicolasCARPi** [comment]
@SWheeler17 yes please make a pr!

**Comment by seyfer** [comment]
I have this issue with `if_neq` right now and cannot continue development. What is the status here?
@SWheeler17 would you make a PR to fix it?

**Comment by SWheeler17** [comment]
@seyfer, upon re-looking at my version of apidoc. I cannot find any instances of `if_neq`. I believe the fix I thought I could make before was due to a mishap I had with git and not being able to see all of the changes (for some reason). If you are running into this issue though please make sure you are on the latest version (if you use npm you should be able to run `npm update -g apidoc`).
